version: "2.4"

volumes:
  tor_data:
  bitcoin_data:
  elements_data:

services:
  tor:
    container_name: ${COMPOSE_PROJECT_NAME}_tor
    image: bitcoinstack/tor:0.4.1.6
    restart: on-failure
    volumes:
      - tor_data:/var/lib/tor/hidden_service
    depends_on:
      - bitcoin
      - elements
    environment:
      TOR_SOCKS_PORT: "172.72.1.10:${TOR_SOCKS_PORT}"
      BITCOIN_TOR_SERVICE_HOSTS: "${BITCOIN_PORT}:bitcoin:${BITCOIN_PORT},${ELEMENTS_PORT}:elements:${ELEMENTS_PORT}"
      BITCOIN_TOR_SERVICE_VERSION: "2"
    ports:
      - "127.0.0.1:${TOR_SOCKS_PORT}:${TOR_SOCKS_PORT}"
    networks:
      solidnet:
        ipv4_address: 172.72.1.10

  bitcoin:
    container_name: ${COMPOSE_PROJECT_NAME}_bitcoin
    image: bitcoinstack/bitcoin:0.18.1-alpine
    command: [
      "-regtest=1",
      "-upnp=0",
      "-server=1",
      "-txindex=1",
      "-dbcache=50",
      "-deprecatedrpc=generate",
      "-dnsseed=0",
      "-dns=0",
      "-onlynet=onion",
      "-port=${BITCOIN_PORT}",
      "-listen=1",
      "-bind=172.72.1.20",
      "-proxy=172.72.1.10:${TOR_SOCKS_PORT}",
      "-regtest.rpcport=${BITCOIN_RPC_PORT}",
      "-regtest.port=${BITCOIN_PORT}",
      "-rpcport=${BITCOIN_RPC_PORT}",
      "-rpcuser=${BITCOIN_RPC_USER}",
      "-rpcpassword=${BITCOIN_RPC_PASSWORD}",
      "-rpcallowip=0.0.0.0/0",
      "-rpcbind=${BITCOIN_HOST}",
      "-zmqpubrawtx=tcp://0.0.0.0:${BITCOIN_ZMQ_TX_PORT}",
      "-zmqpubrawblock=tcp://0.0.0.0:${BITCOIN_ZMQ_BLOCK_PORT}",
      "-zmqpubhashblock=tcp://0.0.0.0:${BITCOIN_ZMQ_BLOCK_PORT}"
    ]
    ports:
      - "127.0.0.1:${BITCOIN_RPC_PORT}:${BITCOIN_RPC_PORT}"
    volumes:
      - bitcoin_data:/home/bitcoin/.bitcoin
    networks:
      solidnet:
        ipv4_address: 172.72.1.20

  elements:
    container_name: ${COMPOSE_PROJECT_NAME}_elements
    image: bitcoinstack/elements:0.18.1.2-alpine
    command: [
      "-chain=liquid-regtest",
      "-validatepegin=1",
      "-initialfreecoins=0",
      "-upnp=0",
      "-server=1",
      "-txindex=1",
      "-dbcache=50",
      "-deprecatedrpc=generate",
      "-dnsseed=0",
      "-dns=0",
      "-onlynet=onion",
      "-port=${ELEMENTS_PORT}",
      "-listen=1",
      "-bind=172.72.1.30",
      "-proxy=172.72.1.10:${TOR_SOCKS_PORT}",
      "-rpcport=${ELEMENTS_RPC_PORT}",
      "-rpcuser=${ELEMENTS_RPC_USER}",
      "-rpcpassword=${ELEMENTS_RPC_PASSWORD}",
      "-rpcallowip=0.0.0.0/0",
      "-rpcbind=${ELEMENTS_HOST}",
      "-zmqpubrawtx=tcp://0.0.0.0:${ELEMENTS_ZMQ_TX_PORT}",
      "-zmqpubhashblock=tcp://0.0.0.0:${ELEMENTS_ZMQ_BLOCK_PORT}",
      "-mainchainrpchost=${BITCOIN_HOST}",
      "-mainchainrpcport=${BITCOIN_RPC_PORT}",
      "-mainchainrpcuser=${BITCOIN_RPC_USER}",
      "-mainchainrpcpassword=${BITCOIN_RPC_PASSWORD}"
    ]
    depends_on:
      - bitcoin
    ports:
      - "127.0.0.1:${ELEMENTS_RPC_PORT}:${ELEMENTS_RPC_PORT}"
    volumes:
      - elements_data:/home/elements/.elements
    networks:
      solidnet:
        ipv4_address: 172.72.1.30

networks:
  solidnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.72.1.0/24